// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRM.Data;

#nullable disable

namespace SRM.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SRM.Shared.Entities.CapDeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CapDeTai", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.CongBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChiSoTacDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DiemHoiDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DongTacGias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileMinhChungBaiBao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Ky")
                        .HasColumnType("int");

                    b.Property<string>("LinkBaiBao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkMinhChungLoaiQ")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkMinhChungTapChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiHoTroChiPhi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiQ")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCongBo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGuiDang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NoiDangBaoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("PhanChiaSuDongGop")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TacGiaChinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TacGiaLienHe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Tap")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenHoiDong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenTapChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThanhQuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("Trang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NoiDangBaoId");

                    b.HasIndex("ThanhQuaId");

                    b.ToTable("CongBo", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.DeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanBoThamGias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CapDeTaiId")
                        .HasColumnType("int");

                    b.Property<string>("ChuNhiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DonViChuTriId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("HoSoNghiemThu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoSoSanPham")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("KinhPhiHangNam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucTieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanChiaSuDongGop")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TongKinhPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapDeTaiId");

                    b.HasIndex("DonViChuTriId");

                    b.ToTable("DeTai", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DonVi", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.DonViChuTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DonViChuTri", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.HoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuNhiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DuongDan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileDinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("KinhPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LoaiHoatDongId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanChiaSuDongGop")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoTiet")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhVienThamGia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiHoatDongId");

                    b.ToTable("HoatDong", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.LoaiHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("LoaiHoatDong", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.LyLichKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucDanhKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucDanhNghienCuu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuHienTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganhDaoDao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganhThacSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganhTienSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoaiCoQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeDaoTaoDaiHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocViCaoNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoNgoaiNgu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoNgoaiNgu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamCapBangThacSi")
                        .HasColumnType("int");

                    b.Property<int?>("NamCapBangTienSi")
                        .HasColumnType("int");

                    b.Property<string>("NamNhanHocVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamTotNghiepDaiHoc")
                        .HasColumnType("int");

                    b.Property<string>("NganhDaiHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgoaiNgu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiCongNhanHocVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDaoTaoDaiHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDaoTaoThacSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDaoTaoTienSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LyLichKhoaHoc", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.NoiDangBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("NoiDangBao", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.QuaTrinhCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiToChuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamBatDau")
                        .HasColumnType("int");

                    b.Property<int?>("NamKetThuc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("ToChucCongTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ViTriCongTac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("QuaTrinhCongTac");
                });

            modelBuilder.Entity("SRM.Shared.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giảng viên",
                            NormalizedName = "GIẢNG VIÊN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sinh viên",
                            NormalizedName = "SINH VIÊN"
                        });
                });

            modelBuilder.Entity("SRM.Shared.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.ThanhQua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ThanhQua", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN123",
                            PasswordHash = "AQAAAAIAAYagAAAAEEXMEGGZAfbpqnVi2Ei9taVel/ImJ2UPWjQtkwQPww9Xt7Vxv2JaclNg8M4hojbRMg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin123"
                        });
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("RoleId");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("SRM.Shared.Entities.CongBo", b =>
                {
                    b.HasOne("SRM.Shared.Entities.NoiDangBao", "NoiDangBao")
                        .WithMany("CongBos")
                        .HasForeignKey("NoiDangBaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRM.Shared.Entities.ThanhQua", "ThanhQua")
                        .WithMany("CongBos")
                        .HasForeignKey("ThanhQuaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NoiDangBao");

                    b.Navigation("ThanhQua");
                });

            modelBuilder.Entity("SRM.Shared.Entities.DeTai", b =>
                {
                    b.HasOne("SRM.Shared.Entities.CapDeTai", "CapDeTai")
                        .WithMany("DeTais")
                        .HasForeignKey("CapDeTaiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRM.Shared.Entities.DonViChuTri", "DonViChuTri")
                        .WithMany("DeTais")
                        .HasForeignKey("DonViChuTriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CapDeTai");

                    b.Navigation("DonViChuTri");
                });

            modelBuilder.Entity("SRM.Shared.Entities.HoatDong", b =>
                {
                    b.HasOne("SRM.Shared.Entities.LoaiHoatDong", "LoaiHoatDong")
                        .WithMany("HoatDongs")
                        .HasForeignKey("LoaiHoatDongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LoaiHoatDong");
                });

            modelBuilder.Entity("SRM.Shared.Entities.LyLichKhoaHoc", b =>
                {
                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithOne("LyLichKhoaHoc")
                        .HasForeignKey("SRM.Shared.Entities.LyLichKhoaHoc", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.QuaTrinhCongTac", b =>
                {
                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithOne("QuaTrinhCongTac")
                        .HasForeignKey("SRM.Shared.Entities.QuaTrinhCongTac", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.RoleClaim", b =>
                {
                    b.HasOne("SRM.Shared.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SRM.Shared.Entities.User", b =>
                {
                    b.HasOne("SRM.Shared.Entities.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId");

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserClaim", b =>
                {
                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserLogin", b =>
                {
                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserRole", b =>
                {
                    b.HasOne("SRM.Shared.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.UserToken", b =>
                {
                    b.HasOne("SRM.Shared.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRM.Shared.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRM.Shared.Entities.CapDeTai", b =>
                {
                    b.Navigation("DeTais");
                });

            modelBuilder.Entity("SRM.Shared.Entities.DonViChuTri", b =>
                {
                    b.Navigation("DeTais");
                });

            modelBuilder.Entity("SRM.Shared.Entities.LoaiHoatDong", b =>
                {
                    b.Navigation("HoatDongs");
                });

            modelBuilder.Entity("SRM.Shared.Entities.NoiDangBao", b =>
                {
                    b.Navigation("CongBos");
                });

            modelBuilder.Entity("SRM.Shared.Entities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SRM.Shared.Entities.ThanhQua", b =>
                {
                    b.Navigation("CongBos");
                });

            modelBuilder.Entity("SRM.Shared.Entities.User", b =>
                {
                    b.Navigation("LyLichKhoaHoc");

                    b.Navigation("QuaTrinhCongTac");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
